import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AutoLogoutWrapper from "@/components/AutoLogoutWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OctaMart",
  description: "Generated by Kelompok 8",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AutoLogoutWrapper>
          {children}
        </AutoLogoutWrapper>
      </body>
    </html>
  );
}
